### PR TITLE
docs: hacktoberfest announcement and seo

### PR DESCRIPTION
**Pull request by Abdulmumin1**

### CODE REVIEW

**Comment by vi1js** [comment]
can you please tell me where should i start to contribute for the hactoberfest in this repositories  good first issue
or is this repository availabe for  hactoberfest 2024? please

**Comment by Abdulmumin1** [comment]
Thanks @wenayy  for your interest in devcanvas!

Super Apologies for the late response.

haven't really found the time to document and create the issues with devcanvas, you can start with that, raising issues is also a form of contribution.

One issue though you can work on is the js console styling, which i haven't properly implemented.
i'm also trying to make it resizable vertically so that you can adjust the height.

image

**Comment by wenayy** [comment]
ok sure i will look on it can i also raise issue

**Comment by Abdulmumin1** [comment]
Sure man!

Thanks 💛

**Pull request merged**
